# Generated by Django 4.2 on 2023-04-29 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='add_dat',
            new_name='add_date',
        ),
    ]
